### PR TITLE
Replace Open state with Acknowledged state

### PR DESCRIPTION
**Pull request by chriscarter90**

### CODE REVIEW

**Comment by oskarpearson** [comment]
LGTM - can I check if we need to do a data migration to match? I'm assuming not, since we don't have any real info in the db...

**Comment by chriscarter90** [comment]
Good point, not sure. Probably can't hurt.

**Comment by ansonK** [comment]
Yes please add a data migration to this. Good rule of thumb is any PR that makes changes that relies on a dataset should include a migration so it will work regardless of whether the target environment has data or not

**Comment by chriscarter90** [comment]
@ansonK @oskarpearson Poke. :cactus:

**Comment by oskarpearson** [comment]
Looks good to me.

**Pull request merged**
